version: "3.7"
services:
  apache:
    image: test/phpapache
    container_name: myapache
    depends_on: 
    - mysql
    build:
      context: .
      dockerfile: Dockerfile-apache
    ports:
    - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f", "http:/localhost"]
      timeout: 10s
      interval: 6s
      retries: 3
  mysql:
    image: mysql:latest
    environment:
    - "MYSQL_ROOT_PASSWORD=1234"
#    logging:
#      driver: none
    volumes:
    - db:/var/lib/mysql
    - /dev/shm:/dev/shm
    restart: unless-stopped
volumes:
  db:
